# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Install packages
      run: |
        npm i
        cd client/
        npm i
    - name: Create .env
      run: |
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PWD=${{ secrets.DB_PWD }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "SECRET=${{ secrets.SECRET }}" >> .env
        echo "DB_DB=${{ secrets.DB_DB }}" >> .env
        echo "DEPLOY=true" >> .env
    - name: Create SSL key and cert
      run: |
        echo "${{ secrets.CRT }}" > server.crt
        echo "${{ secrets.KEY }}" > server.key
    - name: Build react
      run: | 
        cd client/
        sudo npm run build 
        sudo chmod -R ugo+rwX .
    - name: Run server
      run: |
        pm2 restart server.js
